cors:
  enabled: true

feign:
  client.config.default:
    loggerLevel: FULL

logging:
  level:
    org:
      hibernate:
        type: TRACE
      springframework:
        web: DEBUG
    com.sandrocaseiro.apitemplate.clients: DEBUG

server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: template
    password: template
  jpa:
    properties:
      hibernate:
        default_schema: template
        format_sql: true
        type: TRACE
    show-sql: true
  liquibase:
    change-log: classpath:changelog.xml
    enabled: true
    liquibase-schema: template
