feign:
  client.config.default:
    loggerLevel: basic

logging:
  config: classpath:logs/log4j2-spring.dev.xml

spring:
  datasource:
    url: "jdbc:h2:mem:testdb;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS TEMPLATE\\;SET SCHEMA_SEARCH_PATH TEMPLATE;"
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2.console.enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: template
  flyway:
    enabled: true
    clean-disabled: false
    schemas: TEMPLATE
    locations: classpath:db/migration/common,classpath:db/migration/test
  main:
    banner-mode: OFF
